# Generated by Django 3.2.15 on 2022-11-30 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('create_ad', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('delete_at', models.CharField(default=False, max_length=10)),
                ('car_brand', models.CharField(max_length=100)),
                ('repair_plan', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True)),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('number_tm', models.IntegerField(verbose_name='Табельный номер')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='ava', verbose_name='Аватар')),
            ],
            options={
                'verbose_name': 'Управляющий',
                'verbose_name_plural': 'Управляющие',
            },
        ),
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacture_name', models.CharField(max_length=50, verbose_name='Названия компании')),
                ('country_of_manufacture', models.CharField(max_length=50, verbose_name='Страна производства')),
                ('date_of_foundation', models.CharField(max_length=50, verbose_name='Дата основания компании')),
                ('history', models.TextField(blank=True, null=True, verbose_name='История компании')),
                ('logo_manuf', models.ImageField(blank=True, null=True, upload_to='logo', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.IntegerField(verbose_name='Размер скидки')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
            },
        ),
        migrations.CreateModel(
            name='Shop_manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True)),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('number_tm', models.IntegerField(verbose_name='Табельный номер')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='ava', verbose_name='Аватар')),
            ],
            options={
                'verbose_name': 'Менеджер по продажам',
                'verbose_name_plural': 'Менеджеры по продажам',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True, verbose_name='Дата основания отдела')),
                ('name_team', models.CharField(max_length=50, verbose_name='Название отдела')),
                ('top_employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.shop_manager', verbose_name='Сотрудник месяца')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название салона')),
                ('sity', models.CharField(max_length=50, verbose_name='Город')),
                ('location', models.CharField(max_length=50, verbose_name='Адрес')),
                ('square', models.IntegerField(blank=True, null=True, verbose_name='Площадь склада,м.кв')),
                ('number_of_seats', models.IntegerField(blank=True, null=True, verbose_name='Количество мест на складе')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_salon', verbose_name='Фото шоурума')),
                ('manager_shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.shop_manager', verbose_name='Менедер по продажам')),
                ('top_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.manager', verbose_name='Управляющий')),
            ],
            options={
                'verbose_name': 'Салон',
                'verbose_name_plural': 'Салоны',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True)),
                ('last_name', models.CharField(max_length=100, verbose_name='Модель автомобиля')),
                ('vin', models.CharField(blank=True, max_length=17, verbose_name='Вин номер')),
                ('car_class', models.CharField(blank=True, max_length=2, verbose_name='Класс автомобиля')),
                ('year_of_release', models.IntegerField(verbose_name='Год выпуска')),
                ('type_body', models.CharField(max_length=50, verbose_name='Тип кузова')),
                ('drive', models.CharField(max_length=50, verbose_name='Тип привода')),
                ('fuel', models.CharField(max_length=50, verbose_name='Вид топлива')),
                ('volume_engine', models.FloatField(verbose_name='Рабочий обьем,куб.см')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('number_of_seats', models.IntegerField(verbose_name='Колличество мест')),
                ('maximum_speed', models.IntegerField(verbose_name='Максимальная скорость,км/ч')),
                ('curb_weight', models.IntegerField(verbose_name='Снаряженная масса,кг')),
                ('euroncap', models.IntegerField(verbose_name='рейтинг безопасности автомобилей euroncap (кол-во звезд)')),
                ('price', models.IntegerField(verbose_name='Цена(y.e.)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='image_car', verbose_name='Фото')),
                ('notes', models.TextField(blank=True, verbose_name='Доп. информация')),
                ('avtosalon_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.stock', verbose_name='Автосалон')),
                ('car_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.manufacture', verbose_name='Марка автомобиля')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
