# Generated by Django 3.2.15 on 2022-11-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacture',
            name='square',
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='history',
            field=models.TextField(blank=True, null=True, verbose_name='История компании'),
        ),
    ]
