# Generated by Django 3.2.15 on 2022-11-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20221116_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='ava', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='shop_manager',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='ava', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='image_car', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='logo_manuf',
            field=models.ImageField(blank=True, null=True, upload_to='logo', verbose_name='Логотип'),
        ),
    ]
