# Generated by Django 3.2.15 on 2022-12-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20221202_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='sale_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена c учетом скидки(y.e.)'),
        ),
    ]
