# Generated by Django 3.2.15 on 2022-11-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20221124_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto_salon', verbose_name='Фото шоурума'),
        ),
    ]
