# Generated by Django 3.2.15 on 2022-12-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_car_sale_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto_service',
            old_name='repair_plan',
            new_name='to_0',
        ),
        migrations.AddField(
            model_name='auto_service',
            name='to_0_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='auto_service',
            name='to_1',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auto_service',
            name='to_1_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='auto_service',
            name='to_2',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auto_service',
            name='to_2_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='auto_service',
            name='to_3',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auto_service',
            name='to_3_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='auto_service',
            name='to_4',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auto_service',
            name='to_4_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='auto_service',
            name='to_5',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auto_service',
            name='to_5_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='auto_service',
            name='to_6',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auto_service',
            name='to_6_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
