# Generated by Django 3.2.15 on 2022-11-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_stock_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('create_ad', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('delete_at', models.CharField(default='False', max_length=10)),
                ('car_brand', models.CharField(max_length=100)),
                ('repair_plan', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
