# Generated by Django 3.2.15 on 2022-12-05 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20221202_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='MothJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_journal', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.shop_manager', unique_for_month='date', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Журнал учета рабочего времени',
                'verbose_name_plural': 'Журналы учета рабочего времени',
            },
        ),
    ]
