# Generated by Django 3.2.15 on 2022-11-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto_service',
            name='delete_at',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
