# Generated by Django 3.2.15 on 2022-12-06 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20221205_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_manager',
            name='manager_team',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.team', verbose_name='Подразделение'),
        ),
    ]
