# Generated by Django 3.2.15 on 2022-12-13 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True)),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('car_model', models.CharField(max_length=50, verbose_name='Модель автомобиля')),
                ('type_of_repair', models.CharField(max_length=50, verbose_name='Вид технического обслуживания')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('service', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.stock', verbose_name='Выберите салон')),
            ],
            options={
                'verbose_name': 'Запись на сервис',
                'verbose_name_plural': 'Записи на сервисное обслуживание',
            },
        ),
    ]
