# Generated by Django 3.2.15 on 2022-12-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='create_at',
            field=models.DateTimeField(auto_created=True, verbose_name='Дата записи  на ТО'),
        ),
    ]
