# Generated by Django 3.2.15 on 2022-12-14 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_record_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.stock', verbose_name='Выберите салон'),
        ),
    ]
